steps:
# proses CI: Build image & push image ke container registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/vhiobot-server', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/vhiobot-server']
# proses CD: Deploy image ke layanan cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 
  'deploy', 
  'vhiobot-server', 
  '--image', 
  'gcr.io/$PROJECT_ID/vhiobot-server', 
  '--set-env-vars', 
  'FIREBASE_SERVICE_ACCOUNT=${_FIREBASE_SERVICE_ACCOUNT}', 
  '--set-env-vars', 
  'DIALOGFLOW_SERVICE_ACCOUNT=${_DIALOGFLOW_SERVICE_ACCOUNT}', 
  '--region', 
  'asia-southeast1',
  '--platform', 
  'managed',
  '--allow-unauthenticated']
